### ISSUE TITLE
npm ERR

### ISSUE THREAD

**Issue by lbatteau** [datocms/generator-datocms-plugin#1]
I'm following the tutorial at https://www.datocms.com/blog/how-to-create-an-inverse-relations-plugin/, but running into an error.

I've created a directory `datocms-readonly-plugin`. Within the directory, I run: `npx -p yo -p generator-datocms-plugin -c 'yo datocms-plugin'`.

I get:
```
npm ERR! path /Users/lbatteau/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/Users/lbatteau/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lbatteau/.npm/_logs/2019-06-18T11_10_00_644Z-debug.log
```

**Comment by matjack1** [comment]
hey @lbatteau I cannot reproduce your error.

Are you sure you are inside the `datocms-readonly-plugin` folder? From the error message it doesn't seem like.

Can you please try again and feel free to reopen this issue if you need to.
